/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package firsts_group.csia;
import java.io.File;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
/**
 *
 * @author Riya
 */
public class Teachers_data extends javax.swing.JFrame {

    /**
     * Creates new form Teachers_data
     */
    public Teachers_data() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        data_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        data_year = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        data_current_salary = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        data_pass = new javax.swing.JTextField();
        data_tc = new javax.swing.JTextField();
        data_awards = new javax.swing.JTextField();
        attendance_yes = new javax.swing.JRadioButton();
        attendance_no = new javax.swing.JRadioButton();
        Attendance_full = new javax.swing.JRadioButton();
        duties_yes = new javax.swing.JRadioButton();
        duties_no = new javax.swing.JRadioButton();
        diploma = new javax.swing.JRadioButton();
        degree = new javax.swing.JRadioButton();
        upgrade_no = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        output = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        update = new javax.swing.JButton();
        new_record = new javax.swing.JButton();
        view = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        log = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        evidence_degree_button = new javax.swing.JButton();
        evidence_diploma_button = new javax.swing.JButton();
        evidence_awards_button = new javax.swing.JButton();
        award_address = new javax.swing.JTextField();
        diploma_address = new javax.swing.JTextField();
        degree_address = new javax.swing.JTextField();
        view_awards = new javax.swing.JButton();
        view_diploma = new javax.swing.JButton();
        view_degree = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        raise = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setForeground(new java.awt.Color(0, 51, 153));

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Teacher's Data");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Name of the Teacher:");

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Year:");

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Current Salary:");

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Does the teacher have attendance of minimum 165 days?");

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Number of remarkable awards achieved by any student in the teacher's subject this year:");

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Has the teacher gone beyond academic duties for students in special circumstances?");

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Has the teacher upgraded his/her academic qualifications?");

        jLabel9.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Pass percentage of the class:");

        jLabel10.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("Number of Transfer certificates issued in the class:");

        data_tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_tcActionPerformed(evt);
            }
        });

        buttonGroup1.add(attendance_yes);
        attendance_yes.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        attendance_yes.setText("Yes");

        buttonGroup1.add(attendance_no);
        attendance_no.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        attendance_no.setText("No");
        attendance_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendance_noActionPerformed(evt);
            }
        });

        buttonGroup1.add(Attendance_full);
        Attendance_full.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        Attendance_full.setText("Full Attendance");
        Attendance_full.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Attendance_fullActionPerformed(evt);
            }
        });

        buttonGroup2.add(duties_yes);
        duties_yes.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        duties_yes.setText("Yes");
        duties_yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duties_yesActionPerformed(evt);
            }
        });

        buttonGroup2.add(duties_no);
        duties_no.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        duties_no.setText("No");

        diploma.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        diploma.setText("Diploma");
        diploma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diplomaActionPerformed(evt);
            }
        });

        degree.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        degree.setText("Degree");
        degree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreeActionPerformed(evt);
            }
        });

        upgrade_no.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        upgrade_no.setText("No");
        upgrade_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upgrade_noActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("Final Value:");

        output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputActionPerformed(evt);
            }
        });

        search.setBackground(new java.awt.Color(255, 255, 255));
        search.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        search.setText("Search");
        search.setBorder(null);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        update.setText("Update");
        update.setBorder(null);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        new_record.setBackground(new java.awt.Color(255, 255, 255));
        new_record.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        new_record.setText("Add New Record");
        new_record.setBorder(null);
        new_record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_recordActionPerformed(evt);
            }
        });

        view.setBackground(new java.awt.Color(255, 255, 255));
        view.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        view.setText("View All Records");
        view.setBorder(null);
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        delete.setText("Delete");
        delete.setBorder(null);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        clear.setText("Clear");
        clear.setBorder(null);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        log.setBackground(new java.awt.Color(255, 255, 255));
        log.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        log.setText("Sign out");
        log.setBorder(null);
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("Teacher ID:");

        evidence_degree_button.setBackground(new java.awt.Color(255, 255, 255));
        evidence_degree_button.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        evidence_degree_button.setText("Attach Evidence file for Degree (optional):");
        evidence_degree_button.setBorder(null);
        evidence_degree_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evidence_degree_buttonActionPerformed(evt);
            }
        });

        evidence_diploma_button.setBackground(new java.awt.Color(255, 255, 255));
        evidence_diploma_button.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        evidence_diploma_button.setText("Attach Evidence file for Diploma (optional):");
        evidence_diploma_button.setBorder(null);
        evidence_diploma_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evidence_diploma_buttonActionPerformed(evt);
            }
        });

        evidence_awards_button.setBackground(new java.awt.Color(255, 255, 255));
        evidence_awards_button.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        evidence_awards_button.setText("Attach Evidence file for Remarkable Awards Achieved (optional):");
        evidence_awards_button.setBorder(null);
        evidence_awards_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evidence_awards_buttonActionPerformed(evt);
            }
        });

        award_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                award_addressActionPerformed(evt);
            }
        });

        view_awards.setBackground(new java.awt.Color(255, 255, 255));
        view_awards.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        view_awards.setText("View");
        view_awards.setBorder(null);
        view_awards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_awardsActionPerformed(evt);
            }
        });

        view_diploma.setBackground(new java.awt.Color(255, 255, 255));
        view_diploma.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        view_diploma.setText("View");
        view_diploma.setBorder(null);
        view_diploma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_diplomaActionPerformed(evt);
            }
        });

        view_degree.setBackground(new java.awt.Color(255, 255, 255));
        view_degree.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        view_degree.setText("View");
        view_degree.setBorder(null);
        view_degree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_degreeActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("Raise:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(evidence_degree_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(evidence_diploma_button, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(degree_address, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(view_degree, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(diploma)
                                                        .addGap(39, 39, 39)
                                                        .addComponent(degree))
                                                    .addComponent(diploma_address, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(view_diploma, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(view_awards, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(upgrade_no, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))))
                                            .addComponent(duties_no, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(1, 1, 1))
                                            .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(99, 99, 99)
                                                .addComponent(log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(data_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(1, 1, 1))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(evidence_awards_button, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(award_address))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(duties_yes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(raise, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(data_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel2)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(data_name, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(29, 29, 29)
                                                        .addComponent(jLabel3))
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(attendance_yes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(data_year, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(data_current_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(attendance_no, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(Attendance_full, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(data_awards)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(new_record, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                            .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(1, 1, 1)))
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(data_name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data_year, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(data_current_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(attendance_no)
                            .addComponent(Attendance_full)
                            .addComponent(attendance_yes))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(data_awards)
                    .addComponent(new_record, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(award_address, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(view_awards, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(evidence_awards_button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(duties_yes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(duties_no)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diploma)
                    .addComponent(degree)
                    .addComponent(upgrade_no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diploma_address, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(evidence_diploma_button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(view_diploma, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(evidence_degree_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(degree_address, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(view_degree, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(data_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(data_tc))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(raise, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void attendance_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendance_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attendance_noActionPerformed

    private void diplomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diplomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diplomaActionPerformed

    private void degreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degreeActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        new Teachers_list().setVisible(true); //This allows the user to view the table (Teachers list) with the needed data.
        dispose();
    }//GEN-LAST:event_viewActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        data_name.setText("");
        data_year.setText("");
        data_current_salary.setText("");
        data_awards.setText("");
        data_pass.setText("");
        data_tc.setText("");
        output.setText("");
        id.setText("");
        buttonGroup1.clearSelection();
        award_address.setText("");
        buttonGroup2.clearSelection();
        diploma.setSelected(false);
        degree.setSelected(false);
        diploma_address.setText("");
        degree_address.setText("");
        raise.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        new Login_screen().setVisible(true); //Exits the respective user's account, allowing any other relevant end-user to use the application.
        dispose();
    }//GEN-LAST:event_logActionPerformed

    private void new_recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_recordActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conne = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/csia?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "riyamani@3002");
            String sqll = "select * from teachers_increment_data where Id = ? and Teacher_name = ? and Year = ?";
            PreparedStatement pstmtt = conne.prepareStatement(sqll);
            pstmtt.setInt(1, Integer.parseInt(id.getText()));
            pstmtt.setString(2, data_name.getText());
            pstmtt.setInt(3, Integer.parseInt(data_year.getText()));
            ResultSet rs = pstmtt.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "This data already exists. Please try again.", "Error", JOptionPane.OK_OPTION);
            }
            else{
                String sql = "insert into teachers_increment_data values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement pstmt = conne.prepareStatement(sql);
                pstmt.setString(1, data_name.getText());
                pstmt.setInt(2, Integer.parseInt(data_year.getText()));
                pstmt.setInt(3, Integer.parseInt(data_current_salary.getText()));
                int outt = Integer.parseInt(data_current_salary.getText());
                String att = "";
                if(attendance_yes.isSelected()){
                    att = attendance_yes.getText();
                    outt = outt + 2000;
                }
                else if(attendance_no.isSelected()){
                    att = attendance_no.getText();
                }
                else if(Attendance_full.isSelected()){
                    att = Attendance_full.getText();
                    outt = outt + 2500;
                }
                pstmt.setString(4, att);
                pstmt.setInt(5, Integer.parseInt(data_awards.getText()));
                if(award_address.getText() != null){
                    outt = outt + ((Integer.parseInt(data_awards.getText())/100)*8000);
                }
                pstmt.setString(6, award_address.getText());
                String aca = "";
                if(duties_yes.isSelected()){
                    aca = duties_yes.getText();
                    outt = outt + 2000;
                }
                else if(duties_no.isSelected()){
                    aca = duties_no.getText();
                }
                pstmt.setString(7, aca);

                String updi = "";
                if(diploma.isSelected()){
                    updi = diploma.getText();
                }
                pstmt.setString(8, updi);
                if(diploma_address.getText() != null){
                    outt = outt + 1000;
                }
                pstmt.setString(9, diploma_address.getText());
                String upde = "";
                if(degree.isSelected()){
                    upde = degree.getText();
                }
                pstmt.setString(10, upde);
                if(degree_address.getText() != null){
                    outt = outt + 2000;
                }
                pstmt.setString(11, degree_address.getText());
                pstmt.setInt(12, Integer.parseInt(data_pass.getText()));
                outt = outt + ((Integer.parseInt(data_pass.getText())/100)*5000);
                pstmt.setInt(13, Integer.parseInt(data_tc.getText()));
                if(Integer.parseInt(data_tc.getText())>=20){
                    outt = outt - 2000;
                }
                pstmt.setInt(14, outt);
                pstmt.setInt(15, Integer.parseInt(id.getText()));
                pstmt.setString(16, "0");

                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "New record added successfully");
            }
        }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        new Teachers_list().setVisible(true);
        dispose();
    }//GEN-LAST:event_new_recordActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/csia?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "riyamani@3002");
            String sql = "select * from teachers_increment_data where Teacher_name = ? and Year = ? and Id = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, data_name.getText());
            pstmt.setInt(2, Integer.parseInt(data_year.getText()));
            pstmt.setInt(3, Integer.parseInt(id.getText()));

            
            ResultSet rs = pstmt.executeQuery();
            if(rs.next()){
                data_name.setText(rs.getString("Teacher_name"));
                data_year.setText(rs.getString("Year"));
                data_current_salary.setText(rs.getString("Current_salary"));
                if(rs.getString("Attendance").equals("Yes")){
                    attendance_yes.doClick();
                }
                else if(rs.getString("Attendance").equals("No")){
                    attendance_no.doClick();
                }
                else if(rs.getString("Attendance").equals("Full Attendance")){
                    Attendance_full.doClick();
                }
                data_awards.setText(rs.getString("Awards"));
                award_address.setText(rs.getString("File_awards_evidence"));
                if(rs.getString("Academic_duties").equals("Yes")){
                    duties_yes.doClick();
                }
                else{
                    duties_no.doClick();
                }
                if(rs.getString("Upgraded_Diploma").equals("Diploma")){
                    diploma.doClick();
                }
                diploma_address.setText(rs.getString("File_diploma_evidence"));
                if(rs.getString("Upgraded_Degree").equals("Degree")){
                    degree.doClick();
                }
                degree_address.setText(rs.getString("File_degree_evidence"));
                data_pass.setText(rs.getString("Pass_percentage"));
                data_tc.setText(rs.getString("Number_of_TCs_issued"));
                output.setText(rs.getString("Salary"));
                raise.setText(rs.getString("Raise"));
            }
            else{{
                JOptionPane.showMessageDialog(null, "Record not found. Note: Please type the name of the teacher and the year and ID to search for the required record.");
            }
            }
            conn.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Record not found. Note: Please type the name of the teacher and the year and ID to search for the required record.");
        }
    }//GEN-LAST:event_searchActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/csia?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "riyamani@3002");
            String sql = "update teachers_increment_data set Teacher_name = ?, Year = ?, Current_salary = ?, Attendance = ?, Awards = ?, File_awards_evidence = ?, Academic_duties = ?, Upgraded_Diploma = ?, File_diploma_evidence = ?, Upgraded_Degree = ?, File_degree_evidence = ?, Pass_percentage = ?, Number_of_TCs_issued = ?, Id = ? where Id = ? and Teacher_name = ? and Year = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, data_name.getText());
            pstmt.setInt(2, Integer.parseInt(data_year.getText()));
            pstmt.setInt(3, Integer.parseInt(data_current_salary.getText()));
            String att = "";
            if(attendance_yes.isSelected()){
                att = attendance_yes.getText();
            }
            else if(attendance_no.isSelected()){
                att = attendance_no.getText();
            }
            else if(Attendance_full.isSelected()){
                att = Attendance_full.getText();
            }
            pstmt.setString(4, att);
            pstmt.setInt(5, Integer.parseInt(data_awards.getText()));
            pstmt.setString(6, award_address.getText());
            String aca = "";
            if(duties_yes.isSelected()){
                aca = duties_yes.getText();
            }
            else if(duties_no.isSelected()){
                aca = duties_no.getText();
            }
            pstmt.setString(7, aca);
            String updi = "";
            if(diploma.isSelected()){
                updi = diploma.getText();
            }
            else{
                updi = "Null";
            }
            pstmt.setString(8, updi);
            String dia = "";
            if(diploma_address.getText() != null){
                dia = diploma_address.getText();
            }
            else{
                dia = "Null";
            }
            pstmt.setString(9, dia);
            String upde = "";
            if(degree.isSelected()){
                upde = degree.getText();
            }
            else{
                upde = "Null";
            }
            pstmt.setString(10, upde);
            String dea = "";
            if(degree_address.getText() != null){
                dea = degree_address.getText();
            }
            else{
                dea = "Null";
            }
            pstmt.setString(11, dea);
            pstmt.setInt(12, Integer.parseInt(data_pass.getText()));
            pstmt.setInt(13, Integer.parseInt(data_tc.getText()));
            pstmt.setInt(14, Integer.parseInt(id.getText()));
            pstmt.setInt(15, Integer.parseInt(id.getText()));
            pstmt.setString(16, data_name.getText());
            pstmt.setInt(17, Integer.parseInt(data_year.getText()));
            pstmt.executeUpdate();
            
            String sqll = "select * from teachers_increment_data where Teacher_name = ? and Year = ? and Id = ?";
            PreparedStatement pstmtt = conn.prepareStatement(sqll);
            pstmtt.setString(1, data_name.getText());
            pstmtt.setInt(2, Integer.parseInt(data_year.getText()));
            pstmtt.setInt(3, Integer.parseInt(id.getText()));
            
            String sqlll = "update teachers_increment_data set Salary = ? where Teacher_name = ? and Year = ? and Id = ?";
            PreparedStatement pstmttt = conn.prepareStatement(sqlll);
            pstmttt.setString(2, data_name.getText());
            pstmttt.setInt(3, Integer.parseInt(data_year.getText()));
            pstmttt.setInt(4, Integer.parseInt(id.getText()));
            
            ResultSet rs = pstmtt.executeQuery();
            if(rs.next()){
                int outt = Integer.parseInt(rs.getString("Current_salary"));
                if(rs.getString("Attendance").equals("Yes")){
                    outt = outt + 2000;
                }
                else if(rs.getString("Attendance").equals("Full Attendance")){
                    outt = outt + 2500;
                }
                if(rs.getString("File_awards_evidence") != null){
                    outt = outt + (((Integer.parseInt(rs.getString("Awards")))/100)*8000);
                }
                if(rs.getString("Academic_duties").equals("Yes")){
                    outt = outt + 2000;
                }
                if(rs.getString("Upgraded_Diploma").equals("Diploma") && !rs.getString("File_diploma_evidence").isBlank()){
                    outt = outt + 1000;
                }
                if(rs.getString("Upgraded_Degree").equals("Degree") && !rs.getString("File_degree_evidence").isBlank()){
                    outt = outt + 2000;
                }
                outt = outt + (((Integer.parseInt(rs.getString("Pass_percentage")))/100)*5000);
                if(Integer.parseInt(rs.getString("Number_of_TCs_issued"))>=20){
                    outt = outt - 2000;
                }
                outt = outt + Integer.parseInt(rs.getString("Raise"));
                pstmttt.setInt(1, outt);
            }
            pstmttt.executeUpdate();
        conn.close();
        JOptionPane.showMessageDialog(null, "Record updated successfully.");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please make sure you add no decimal values or ',' in the numerical data entered.");
        }
        new Teachers_list().setVisible(true);//To show the user whether if the salary has been updated in the table through the database.
        dispose();
    }//GEN-LAST:event_updateActionPerformed

    private void Attendance_fullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Attendance_fullActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Attendance_fullActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/csia?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "riyamani@3002");
            String sqll = "delete from teachers_increment_data where Teacher_name = ? and Year = ? and Id = ?";
            PreparedStatement pstmtt = conn.prepareStatement(sqll);
            pstmtt.setString(1, data_name.getText());
            pstmtt.setInt(2, Integer.parseInt(data_year.getText()));
            pstmtt.setInt(3, Integer.parseInt(id.getText()));
            pstmtt.executeUpdate();
            JOptionPane.showConfirmDialog(null, "Are you sure?");
            
            conn.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        new Teachers_list().setVisible(true); //Shows the user that the data does not exist in the databse anymore through the table (teacher list).
        dispose();
    }//GEN-LAST:event_deleteActionPerformed

    private void upgrade_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upgrade_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upgrade_noActionPerformed

    private void data_tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_tcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data_tcActionPerformed

    private void duties_yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duties_yesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duties_yesActionPerformed

    private void evidence_degree_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evidence_degree_buttonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        degree_address.setText(filename);
    }//GEN-LAST:event_evidence_degree_buttonActionPerformed

    private void outputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputActionPerformed

    private void evidence_diploma_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evidence_diploma_buttonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        diploma_address.setText(filename);
    }//GEN-LAST:event_evidence_diploma_buttonActionPerformed

    private void award_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_award_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_award_addressActionPerformed

    private void evidence_awards_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evidence_awards_buttonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        award_address.setText(filename);
    }//GEN-LAST:event_evidence_awards_buttonActionPerformed

    private void view_awardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_awardsActionPerformed
        try
        {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+award_address.getText().toString());
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error! Please check if the file is attached.");
        }
    }//GEN-LAST:event_view_awardsActionPerformed

    private void view_diplomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_diplomaActionPerformed
        try
        {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+diploma_address.getText().toString());
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error! Please check if the file is attached.");
        }
    }//GEN-LAST:event_view_diplomaActionPerformed

    private void view_degreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_degreeActionPerformed
        try
        {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+degree_address.getText().toString());
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error! Please check if the file is attached.");
        }
    }//GEN-LAST:event_view_degreeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teachers_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teachers_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teachers_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teachers_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teachers_data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Attendance_full;
    private javax.swing.JRadioButton attendance_no;
    private javax.swing.JRadioButton attendance_yes;
    private javax.swing.JTextField award_address;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton clear;
    private javax.swing.JTextField data_awards;
    private javax.swing.JTextField data_current_salary;
    private javax.swing.JTextField data_name;
    private javax.swing.JTextField data_pass;
    private javax.swing.JTextField data_tc;
    private javax.swing.JTextField data_year;
    private javax.swing.JRadioButton degree;
    private javax.swing.JTextField degree_address;
    private javax.swing.JButton delete;
    private javax.swing.JRadioButton diploma;
    private javax.swing.JTextField diploma_address;
    private javax.swing.JRadioButton duties_no;
    private javax.swing.JRadioButton duties_yes;
    private javax.swing.JButton evidence_awards_button;
    private javax.swing.JButton evidence_degree_button;
    private javax.swing.JButton evidence_diploma_button;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton log;
    private javax.swing.JButton new_record;
    private javax.swing.JTextField output;
    private javax.swing.JTextField raise;
    private javax.swing.JButton search;
    private javax.swing.JButton update;
    private javax.swing.JRadioButton upgrade_no;
    private javax.swing.JButton view;
    private javax.swing.JButton view_awards;
    private javax.swing.JButton view_degree;
    private javax.swing.JButton view_diploma;
    // End of variables declaration//GEN-END:variables
}
